name: meetava_pro
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  faker: ^2.1.0
  go_router: ^14.1.4
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  fonts:
    - family: AtHaussAero
      fonts:
        - asset: assets/fonts/AtHaussAero-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/AtHaussAero-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/AtHaussAero-Air.ttf
          weight: 200
        - asset: assets/fonts/AtHaussAero-Regular.ttf
          weight: 400
        - asset: assets/fonts/AtHaussAero-Semibold.ttf
          weight: 600
        - asset: assets/fonts/AtHaussAero-SuperItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/AtHaussAero-SemiboldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/AtHaussAero-RetinaItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/AtHaussAero-Super.ttf
          weight: 800
        - asset: assets/fonts/AtHaussAero-Bold.ttf
          weight: 700
        - asset: assets/fonts/AtHaussAero-Thin.ttf
          weight: 100
        - asset: assets/fonts/AtHaussAero-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/AtHaussAero-Black.ttf
          weight: 900
        - asset: assets/fonts/AtHaussAero-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/AtHaussAero-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/AtHaussAero-Light.ttf
          weight: 300
        - asset: assets/fonts/AtHaussAero-Retina.ttf
          weight: 700
        - asset: assets/fonts/AtHaussAero-AirItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/AtHaussAero-RegularItalic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/AtHaussAero-Medium.ttf
          weight: 500
